// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetComputeprofile
    {
        public static Task<GetComputeprofileResult> InvokeAsync(GetComputeprofileArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetComputeprofileResult>("foreman:index/getComputeprofile:getComputeprofile", args ?? new GetComputeprofileArgs(), options.WithDefaults());

        public static Output<GetComputeprofileResult> Invoke(GetComputeprofileInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetComputeprofileResult>("foreman:index/getComputeprofile:getComputeprofile", args ?? new GetComputeprofileInvokeArgs(), options.WithDefaults());

        public static Output<GetComputeprofileResult> Invoke(GetComputeprofileInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetComputeprofileResult>("foreman:index/getComputeprofile:getComputeprofile", args ?? new GetComputeprofileInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetComputeprofileArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetComputeprofileArgs()
        {
        }
        public static new GetComputeprofileArgs Empty => new GetComputeprofileArgs();
    }

    public sealed class GetComputeprofileInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetComputeprofileInvokeArgs()
        {
        }
        public static new GetComputeprofileInvokeArgs Empty => new GetComputeprofileInvokeArgs();
    }


    [OutputType]
    public sealed class GetComputeprofileResult
    {
        public readonly ImmutableArray<Outputs.GetComputeprofileComputeAttributeResult> ComputeAttributes;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetComputeprofileResult(
            ImmutableArray<Outputs.GetComputeprofileComputeAttributeResult> computeAttributes,

            string id,

            string name)
        {
            ComputeAttributes = computeAttributes;
            Id = id;
            Name = name;
        }
    }
}
