// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetDefaulttemplate
    {
        public static Task<GetDefaulttemplateResult> InvokeAsync(GetDefaulttemplateArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDefaulttemplateResult>("foreman:index/getDefaulttemplate:getDefaulttemplate", args ?? new GetDefaulttemplateArgs(), options.WithDefaults());

        public static Output<GetDefaulttemplateResult> Invoke(GetDefaulttemplateInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDefaulttemplateResult>("foreman:index/getDefaulttemplate:getDefaulttemplate", args ?? new GetDefaulttemplateInvokeArgs(), options.WithDefaults());

        public static Output<GetDefaulttemplateResult> Invoke(GetDefaulttemplateInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetDefaulttemplateResult>("foreman:index/getDefaulttemplate:getDefaulttemplate", args ?? new GetDefaulttemplateInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDefaulttemplateArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetDefaulttemplateArgs()
        {
        }
        public static new GetDefaulttemplateArgs Empty => new GetDefaulttemplateArgs();
    }

    public sealed class GetDefaulttemplateInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetDefaulttemplateInvokeArgs()
        {
        }
        public static new GetDefaulttemplateInvokeArgs Empty => new GetDefaulttemplateInvokeArgs();
    }


    [OutputType]
    public sealed class GetDefaulttemplateResult
    {
        public readonly bool __meta_;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly int OperatingsystemId;
        public readonly int ProvisioningtemplateId;
        public readonly int TemplatekindId;

        [OutputConstructor]
        private GetDefaulttemplateResult(
            bool __meta_,

            string id,

            string name,

            int operatingsystemId,

            int provisioningtemplateId,

            int templatekindId)
        {
            this.__meta_ = __meta_;
            Id = id;
            Name = name;
            OperatingsystemId = operatingsystemId;
            ProvisioningtemplateId = provisioningtemplateId;
            TemplatekindId = templatekindId;
        }
    }
}
