// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetHttpproxy
    {
        public static Task<GetHttpproxyResult> InvokeAsync(GetHttpproxyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetHttpproxyResult>("foreman:index/getHttpproxy:getHttpproxy", args ?? new GetHttpproxyArgs(), options.WithDefaults());

        public static Output<GetHttpproxyResult> Invoke(GetHttpproxyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetHttpproxyResult>("foreman:index/getHttpproxy:getHttpproxy", args ?? new GetHttpproxyInvokeArgs(), options.WithDefaults());

        public static Output<GetHttpproxyResult> Invoke(GetHttpproxyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetHttpproxyResult>("foreman:index/getHttpproxy:getHttpproxy", args ?? new GetHttpproxyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetHttpproxyArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetHttpproxyArgs()
        {
        }
        public static new GetHttpproxyArgs Empty => new GetHttpproxyArgs();
    }

    public sealed class GetHttpproxyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetHttpproxyInvokeArgs()
        {
        }
        public static new GetHttpproxyInvokeArgs Empty => new GetHttpproxyInvokeArgs();
    }


    [OutputType]
    public sealed class GetHttpproxyResult
    {
        public readonly bool __meta_;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string Url;

        [OutputConstructor]
        private GetHttpproxyResult(
            bool __meta_,

            string id,

            string name,

            string url)
        {
            this.__meta_ = __meta_;
            Id = id;
            Name = name;
            Url = url;
        }
    }
}
