// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetKatelloLifecycleEnvironment
    {
        public static Task<GetKatelloLifecycleEnvironmentResult> InvokeAsync(GetKatelloLifecycleEnvironmentArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetKatelloLifecycleEnvironmentResult>("foreman:index/getKatelloLifecycleEnvironment:getKatelloLifecycleEnvironment", args ?? new GetKatelloLifecycleEnvironmentArgs(), options.WithDefaults());

        public static Output<GetKatelloLifecycleEnvironmentResult> Invoke(GetKatelloLifecycleEnvironmentInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetKatelloLifecycleEnvironmentResult>("foreman:index/getKatelloLifecycleEnvironment:getKatelloLifecycleEnvironment", args ?? new GetKatelloLifecycleEnvironmentInvokeArgs(), options.WithDefaults());

        public static Output<GetKatelloLifecycleEnvironmentResult> Invoke(GetKatelloLifecycleEnvironmentInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetKatelloLifecycleEnvironmentResult>("foreman:index/getKatelloLifecycleEnvironment:getKatelloLifecycleEnvironment", args ?? new GetKatelloLifecycleEnvironmentInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetKatelloLifecycleEnvironmentArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetKatelloLifecycleEnvironmentArgs()
        {
        }
        public static new GetKatelloLifecycleEnvironmentArgs Empty => new GetKatelloLifecycleEnvironmentArgs();
    }

    public sealed class GetKatelloLifecycleEnvironmentInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetKatelloLifecycleEnvironmentInvokeArgs()
        {
        }
        public static new GetKatelloLifecycleEnvironmentInvokeArgs Empty => new GetKatelloLifecycleEnvironmentInvokeArgs();
    }


    [OutputType]
    public sealed class GetKatelloLifecycleEnvironmentResult
    {
        public readonly bool __meta_;
        public readonly string Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Label;
        public readonly bool Library;
        public readonly string Name;
        public readonly int OrganizationId;
        public readonly int PriorId;
        public readonly int SuccessorId;

        [OutputConstructor]
        private GetKatelloLifecycleEnvironmentResult(
            bool __meta_,

            string description,

            string id,

            string label,

            bool library,

            string name,

            int organizationId,

            int priorId,

            int successorId)
        {
            this.__meta_ = __meta_;
            Description = description;
            Id = id;
            Label = label;
            Library = library;
            Name = name;
            OrganizationId = organizationId;
            PriorId = priorId;
            SuccessorId = successorId;
        }
    }
}
