// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetKatelloContentCredential
    {
        public static Task<GetKatelloContentCredentialResult> InvokeAsync(GetKatelloContentCredentialArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetKatelloContentCredentialResult>("foreman:index/getKatelloContentCredential:getKatelloContentCredential", args ?? new GetKatelloContentCredentialArgs(), options.WithDefaults());

        public static Output<GetKatelloContentCredentialResult> Invoke(GetKatelloContentCredentialInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetKatelloContentCredentialResult>("foreman:index/getKatelloContentCredential:getKatelloContentCredential", args ?? new GetKatelloContentCredentialInvokeArgs(), options.WithDefaults());

        public static Output<GetKatelloContentCredentialResult> Invoke(GetKatelloContentCredentialInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetKatelloContentCredentialResult>("foreman:index/getKatelloContentCredential:getKatelloContentCredential", args ?? new GetKatelloContentCredentialInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetKatelloContentCredentialArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetKatelloContentCredentialArgs()
        {
        }
        public static new GetKatelloContentCredentialArgs Empty => new GetKatelloContentCredentialArgs();
    }

    public sealed class GetKatelloContentCredentialInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetKatelloContentCredentialInvokeArgs()
        {
        }
        public static new GetKatelloContentCredentialInvokeArgs Empty => new GetKatelloContentCredentialInvokeArgs();
    }


    [OutputType]
    public sealed class GetKatelloContentCredentialResult
    {
        public readonly string Content;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetKatelloContentCredentialResult(
            string content,

            string id,

            string name)
        {
            Content = content;
            Id = id;
            Name = name;
        }
    }
}
