// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetMedia
    {
        public static Task<GetMediaResult> InvokeAsync(GetMediaArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetMediaResult>("foreman:index/getMedia:getMedia", args ?? new GetMediaArgs(), options.WithDefaults());

        public static Output<GetMediaResult> Invoke(GetMediaInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetMediaResult>("foreman:index/getMedia:getMedia", args ?? new GetMediaInvokeArgs(), options.WithDefaults());

        public static Output<GetMediaResult> Invoke(GetMediaInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetMediaResult>("foreman:index/getMedia:getMedia", args ?? new GetMediaInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetMediaArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetMediaArgs()
        {
        }
        public static new GetMediaArgs Empty => new GetMediaArgs();
    }

    public sealed class GetMediaInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetMediaInvokeArgs()
        {
        }
        public static new GetMediaInvokeArgs Empty => new GetMediaInvokeArgs();
    }


    [OutputType]
    public sealed class GetMediaResult
    {
        public readonly bool __meta_;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly ImmutableArray<int> OperatingsystemIds;
        public readonly string OsFamily;
        public readonly string Path;

        [OutputConstructor]
        private GetMediaResult(
            bool __meta_,

            string id,

            string name,

            ImmutableArray<int> operatingsystemIds,

            string osFamily,

            string path)
        {
            this.__meta_ = __meta_;
            Id = id;
            Name = name;
            OperatingsystemIds = operatingsystemIds;
            OsFamily = osFamily;
            Path = path;
        }
    }
}
