// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetPuppetclass
    {
        public static Task<GetPuppetclassResult> InvokeAsync(GetPuppetclassArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetPuppetclassResult>("foreman:index/getPuppetclass:getPuppetclass", args ?? new GetPuppetclassArgs(), options.WithDefaults());

        public static Output<GetPuppetclassResult> Invoke(GetPuppetclassInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetPuppetclassResult>("foreman:index/getPuppetclass:getPuppetclass", args ?? new GetPuppetclassInvokeArgs(), options.WithDefaults());

        public static Output<GetPuppetclassResult> Invoke(GetPuppetclassInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetPuppetclassResult>("foreman:index/getPuppetclass:getPuppetclass", args ?? new GetPuppetclassInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetPuppetclassArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetPuppetclassArgs()
        {
        }
        public static new GetPuppetclassArgs Empty => new GetPuppetclassArgs();
    }

    public sealed class GetPuppetclassInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetPuppetclassInvokeArgs()
        {
        }
        public static new GetPuppetclassInvokeArgs Empty => new GetPuppetclassInvokeArgs();
    }


    [OutputType]
    public sealed class GetPuppetclassResult
    {
        public readonly bool __meta_;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetPuppetclassResult(
            bool __meta_,

            string id,

            string name)
        {
            this.__meta_ = __meta_;
            Id = id;
            Name = name;
        }
    }
}
