// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetSmartproxy
    {
        public static Task<GetSmartproxyResult> InvokeAsync(GetSmartproxyArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSmartproxyResult>("foreman:index/getSmartproxy:getSmartproxy", args ?? new GetSmartproxyArgs(), options.WithDefaults());

        public static Output<GetSmartproxyResult> Invoke(GetSmartproxyInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSmartproxyResult>("foreman:index/getSmartproxy:getSmartproxy", args ?? new GetSmartproxyInvokeArgs(), options.WithDefaults());

        public static Output<GetSmartproxyResult> Invoke(GetSmartproxyInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSmartproxyResult>("foreman:index/getSmartproxy:getSmartproxy", args ?? new GetSmartproxyInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSmartproxyArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetSmartproxyArgs()
        {
        }
        public static new GetSmartproxyArgs Empty => new GetSmartproxyArgs();
    }

    public sealed class GetSmartproxyInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetSmartproxyInvokeArgs()
        {
        }
        public static new GetSmartproxyInvokeArgs Empty => new GetSmartproxyInvokeArgs();
    }


    [OutputType]
    public sealed class GetSmartproxyResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly string Url;

        [OutputConstructor]
        private GetSmartproxyResult(
            string id,

            string name,

            string url)
        {
            Id = id;
            Name = name;
            Url = url;
        }
    }
}
