// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetSetting
    {
        public static Task<GetSettingResult> InvokeAsync(GetSettingArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetSettingResult>("foreman:index/getSetting:getSetting", args ?? new GetSettingArgs(), options.WithDefaults());

        public static Output<GetSettingResult> Invoke(GetSettingInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetSettingResult>("foreman:index/getSetting:getSetting", args ?? new GetSettingInvokeArgs(), options.WithDefaults());

        public static Output<GetSettingResult> Invoke(GetSettingInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetSettingResult>("foreman:index/getSetting:getSetting", args ?? new GetSettingInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetSettingArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetSettingArgs()
        {
        }
        public static new GetSettingArgs Empty => new GetSettingArgs();
    }

    public sealed class GetSettingInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetSettingInvokeArgs()
        {
        }
        public static new GetSettingInvokeArgs Empty => new GetSettingInvokeArgs();
    }


    [OutputType]
    public sealed class GetSettingResult
    {
        public readonly string CategoryName;
        public readonly string Default;
        public readonly string Description;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;
        public readonly bool Readonly;
        public readonly string SettingsType;
        public readonly string Value;

        [OutputConstructor]
        private GetSettingResult(
            string categoryName,

            string @default,

            string description,

            string id,

            string name,

            bool @readonly,

            string settingsType,

            string value)
        {
            CategoryName = categoryName;
            Default = @default;
            Description = description;
            Id = id;
            Name = name;
            Readonly = @readonly;
            SettingsType = settingsType;
            Value = value;
        }
    }
}
