// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetTemplatekind
    {
        public static Task<GetTemplatekindResult> InvokeAsync(GetTemplatekindArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTemplatekindResult>("foreman:index/getTemplatekind:getTemplatekind", args ?? new GetTemplatekindArgs(), options.WithDefaults());

        public static Output<GetTemplatekindResult> Invoke(GetTemplatekindInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTemplatekindResult>("foreman:index/getTemplatekind:getTemplatekind", args ?? new GetTemplatekindInvokeArgs(), options.WithDefaults());

        public static Output<GetTemplatekindResult> Invoke(GetTemplatekindInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTemplatekindResult>("foreman:index/getTemplatekind:getTemplatekind", args ?? new GetTemplatekindInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetTemplatekindArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetTemplatekindArgs()
        {
        }
        public static new GetTemplatekindArgs Empty => new GetTemplatekindArgs();
    }

    public sealed class GetTemplatekindInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetTemplatekindInvokeArgs()
        {
        }
        public static new GetTemplatekindInvokeArgs Empty => new GetTemplatekindInvokeArgs();
    }


    [OutputType]
    public sealed class GetTemplatekindResult
    {
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetTemplatekindResult(
            string id,

            string name)
        {
            Id = id;
            Name = name;
        }
    }
}
