// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetTemplateinput
    {
        public static Task<GetTemplateinputResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetTemplateinputResult>("foreman:index/getTemplateinput:getTemplateinput", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetTemplateinputResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetTemplateinputResult>("foreman:index/getTemplateinput:getTemplateinput", InvokeArgs.Empty, options.WithDefaults());

        public static Output<GetTemplateinputResult> Invoke(InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetTemplateinputResult>("foreman:index/getTemplateinput:getTemplateinput", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetTemplateinputResult
    {
        public readonly bool Advanced;
        public readonly string Default;
        public readonly string Description;
        public readonly string FactName;
        public readonly bool HiddenValue;
        public readonly string Id;
        public readonly string InputType;
        public readonly string Name;
        public readonly string PuppetClassName;
        public readonly string PuppetParameterName;
        public readonly bool Required;
        public readonly string ResourceType;
        public readonly int TemplateId;
        public readonly string ValueType;
        public readonly string VariableName;

        [OutputConstructor]
        private GetTemplateinputResult(
            bool advanced,

            string @default,

            string description,

            string factName,

            bool hiddenValue,

            string id,

            string inputType,

            string name,

            string puppetClassName,

            string puppetParameterName,

            bool required,

            string resourceType,

            int templateId,

            string valueType,

            string variableName)
        {
            Advanced = advanced;
            Default = @default;
            Description = description;
            FactName = factName;
            HiddenValue = hiddenValue;
            Id = id;
            InputType = inputType;
            Name = name;
            PuppetClassName = puppetClassName;
            PuppetParameterName = puppetParameterName;
            Required = required;
            ResourceType = resourceType;
            TemplateId = templateId;
            ValueType = valueType;
            VariableName = variableName;
        }
    }
}
