// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    public static class GetUsergroup
    {
        public static Task<GetUsergroupResult> InvokeAsync(GetUsergroupArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetUsergroupResult>("foreman:index/getUsergroup:getUsergroup", args ?? new GetUsergroupArgs(), options.WithDefaults());

        public static Output<GetUsergroupResult> Invoke(GetUsergroupInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetUsergroupResult>("foreman:index/getUsergroup:getUsergroup", args ?? new GetUsergroupInvokeArgs(), options.WithDefaults());

        public static Output<GetUsergroupResult> Invoke(GetUsergroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetUsergroupResult>("foreman:index/getUsergroup:getUsergroup", args ?? new GetUsergroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetUsergroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetUsergroupArgs()
        {
        }
        public static new GetUsergroupArgs Empty => new GetUsergroupArgs();
    }

    public sealed class GetUsergroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetUsergroupInvokeArgs()
        {
        }
        public static new GetUsergroupInvokeArgs Empty => new GetUsergroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetUsergroupResult
    {
        public readonly bool Admin;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetUsergroupResult(
            bool admin,

            string id,

            string name)
        {
            Admin = admin;
            Id = id;
            Name = name;
        }
    }
}
