// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    [ForemanResourceType("foreman:index/katelloProduct:KatelloProduct")]
    public partial class KatelloProduct : global::Pulumi.CustomResource
    {
        /// <summary>
        /// @SUMMARY Poducts are mostly operating systems to which repositories are assigned.
        /// </summary>
        [Output("__meta_")]
        public Output<bool> __meta_ { get; private set; } = null!;

        /// <summary>
        /// Product description.@EXAMPLE "A product description"
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Identifier of the GPG key.@EXAMPLE
        /// </summary>
        [Output("gpgKeyId")]
        public Output<int?> GpgKeyId { get; private set; } = null!;

        /// <summary>
        /// Label for the product. Cannot be changed after creation. By default set to the name, with underscores as spaces
        /// replacement. @EXAMPLE
        /// </summary>
        [Output("label")]
        public Output<string> Label { get; private set; } = null!;

        /// <summary>
        /// Product name.@EXAMPLE "Debian 10"
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Idenifier of the SSL CA Cert.@EXAMPLE
        /// </summary>
        [Output("sslCaCertId")]
        public Output<int?> SslCaCertId { get; private set; } = null!;

        /// <summary>
        /// Identifier of the SSL Client Cert.@EXAMPLE
        /// </summary>
        [Output("sslClientCertId")]
        public Output<int?> SslClientCertId { get; private set; } = null!;

        /// <summary>
        /// Identifier of the SSL Client Key.@EXAMPLE
        /// </summary>
        [Output("sslClientKeyId")]
        public Output<int?> SslClientKeyId { get; private set; } = null!;

        /// <summary>
        /// Plan numeric identifier.@EXAMPLE
        /// </summary>
        [Output("syncPlanId")]
        public Output<int?> SyncPlanId { get; private set; } = null!;


        /// <summary>
        /// Create a KatelloProduct resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public KatelloProduct(string name, KatelloProductArgs? args = null, CustomResourceOptions? options = null)
            : base("foreman:index/katelloProduct:KatelloProduct", name, args ?? new KatelloProductArgs(), MakeResourceOptions(options, ""))
        {
        }

        private KatelloProduct(string name, Input<string> id, KatelloProductState? state = null, CustomResourceOptions? options = null)
            : base("foreman:index/katelloProduct:KatelloProduct", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing KatelloProduct resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static KatelloProduct Get(string name, Input<string> id, KatelloProductState? state = null, CustomResourceOptions? options = null)
        {
            return new KatelloProduct(name, id, state, options);
        }
    }

    public sealed class KatelloProductArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Product description.@EXAMPLE "A product description"
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Identifier of the GPG key.@EXAMPLE
        /// </summary>
        [Input("gpgKeyId")]
        public Input<int>? GpgKeyId { get; set; }

        /// <summary>
        /// Label for the product. Cannot be changed after creation. By default set to the name, with underscores as spaces
        /// replacement. @EXAMPLE
        /// </summary>
        [Input("label")]
        public Input<string>? Label { get; set; }

        /// <summary>
        /// Product name.@EXAMPLE "Debian 10"
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Idenifier of the SSL CA Cert.@EXAMPLE
        /// </summary>
        [Input("sslCaCertId")]
        public Input<int>? SslCaCertId { get; set; }

        /// <summary>
        /// Identifier of the SSL Client Cert.@EXAMPLE
        /// </summary>
        [Input("sslClientCertId")]
        public Input<int>? SslClientCertId { get; set; }

        /// <summary>
        /// Identifier of the SSL Client Key.@EXAMPLE
        /// </summary>
        [Input("sslClientKeyId")]
        public Input<int>? SslClientKeyId { get; set; }

        /// <summary>
        /// Plan numeric identifier.@EXAMPLE
        /// </summary>
        [Input("syncPlanId")]
        public Input<int>? SyncPlanId { get; set; }

        public KatelloProductArgs()
        {
        }
        public static new KatelloProductArgs Empty => new KatelloProductArgs();
    }

    public sealed class KatelloProductState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// @SUMMARY Poducts are mostly operating systems to which repositories are assigned.
        /// </summary>
        [Input("__meta_")]
        public Input<bool>? __meta_ { get; set; }

        /// <summary>
        /// Product description.@EXAMPLE "A product description"
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Identifier of the GPG key.@EXAMPLE
        /// </summary>
        [Input("gpgKeyId")]
        public Input<int>? GpgKeyId { get; set; }

        /// <summary>
        /// Label for the product. Cannot be changed after creation. By default set to the name, with underscores as spaces
        /// replacement. @EXAMPLE
        /// </summary>
        [Input("label")]
        public Input<string>? Label { get; set; }

        /// <summary>
        /// Product name.@EXAMPLE "Debian 10"
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Idenifier of the SSL CA Cert.@EXAMPLE
        /// </summary>
        [Input("sslCaCertId")]
        public Input<int>? SslCaCertId { get; set; }

        /// <summary>
        /// Identifier of the SSL Client Cert.@EXAMPLE
        /// </summary>
        [Input("sslClientCertId")]
        public Input<int>? SslClientCertId { get; set; }

        /// <summary>
        /// Identifier of the SSL Client Key.@EXAMPLE
        /// </summary>
        [Input("sslClientKeyId")]
        public Input<int>? SslClientKeyId { get; set; }

        /// <summary>
        /// Plan numeric identifier.@EXAMPLE
        /// </summary>
        [Input("syncPlanId")]
        public Input<int>? SyncPlanId { get; set; }

        public KatelloProductState()
        {
        }
        public static new KatelloProductState Empty => new KatelloProductState();
    }
}
