// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman
{
    [ForemanResourceType("foreman:index/smartproxy:Smartproxy")]
    public partial class Smartproxy : global::Pulumi.CustomResource
    {
        /// <summary>
        /// @SUMMARY Smart proxies provide an API for a higher-level orchestration tool. Foreman supports the following smart
        /// proxies: DHCP (ISC DHCP &amp; MS DHCP servers), DNS (bind &amp; MS DNS servers), Puppet &gt;= 0.24.x, Puppet CA, Realm (FreeIPA),
        /// Templates, TFTP.
        /// </summary>
        [Output("__meta_")]
        public Output<bool> __meta_ { get; private set; } = null!;

        /// <summary>
        /// The name of the smart proxy. @EXAMPLE "dns.dc1.company.com"
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Uniform resource locator of the proxy. @EXAMPLE "https://dns.dc1.company.com:8443"
        /// </summary>
        [Output("url")]
        public Output<string> Url { get; private set; } = null!;


        /// <summary>
        /// Create a Smartproxy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Smartproxy(string name, SmartproxyArgs args, CustomResourceOptions? options = null)
            : base("foreman:index/smartproxy:Smartproxy", name, args ?? new SmartproxyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Smartproxy(string name, Input<string> id, SmartproxyState? state = null, CustomResourceOptions? options = null)
            : base("foreman:index/smartproxy:Smartproxy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Smartproxy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Smartproxy Get(string name, Input<string> id, SmartproxyState? state = null, CustomResourceOptions? options = null)
        {
            return new Smartproxy(name, id, state, options);
        }
    }

    public sealed class SmartproxyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The name of the smart proxy. @EXAMPLE "dns.dc1.company.com"
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Uniform resource locator of the proxy. @EXAMPLE "https://dns.dc1.company.com:8443"
        /// </summary>
        [Input("url", required: true)]
        public Input<string> Url { get; set; } = null!;

        public SmartproxyArgs()
        {
        }
        public static new SmartproxyArgs Empty => new SmartproxyArgs();
    }

    public sealed class SmartproxyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// @SUMMARY Smart proxies provide an API for a higher-level orchestration tool. Foreman supports the following smart
        /// proxies: DHCP (ISC DHCP &amp; MS DHCP servers), DNS (bind &amp; MS DNS servers), Puppet &gt;= 0.24.x, Puppet CA, Realm (FreeIPA),
        /// Templates, TFTP.
        /// </summary>
        [Input("__meta_")]
        public Input<bool>? __meta_ { get; set; }

        /// <summary>
        /// The name of the smart proxy. @EXAMPLE "dns.dc1.company.com"
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Uniform resource locator of the proxy. @EXAMPLE "https://dns.dc1.company.com:8443"
        /// </summary>
        [Input("url")]
        public Input<string>? Url { get; set; }

        public SmartproxyState()
        {
        }
        public static new SmartproxyState Empty => new SmartproxyState();
    }
}
