// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/masikrus/pulumi-foreman/sdk/go/foreman/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// Whether or not the client should try to authenticate through the HTTP negotiate mechanism. Defaults to `false`.
func GetClientAuthNegotiate(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "foreman:clientAuthNegotiate")
}

// The username to authenticate against Foreman. This can also be set through the environment variable
// `FOREMAN_CLIENT_PASSWORD`. Defaults to `""`.
func GetClientPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "foreman:clientPassword")
}

// Whether or not to verify the server's certificate. Defaults to `false`.
func GetClientTlsInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "foreman:clientTlsInsecure")
}

// The username to authenticate against Foreman. This can also be set through the environment variable
// `FOREMAN_CLIENT_USERNAME`. Defaults to `""`.
func GetClientUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "foreman:clientUsername")
}

// The location for all resources requested and created by the providerDefaults to "0". Set organizationId and locationId
// to a value < 0 if you need to disable Locations and Organizations on Foreman older than 1.21
func GetLocationId(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "foreman:locationId")
}

// The organization for all resource requested and created by the Provider Defaults to "0". Set organizationId and
// locationId to a value < 0 if you need to disable Locations and Organizations on Foreman older than 1.21
func GetOrganizationId(ctx *pulumi.Context) int {
	return config.GetInt(ctx, "foreman:organizationId")
}
func GetProviderLogfile(ctx *pulumi.Context) string {
	return config.Get(ctx, "foreman:providerLogfile")
}

// The level of verbosity for the provider's log file. This setting determines which types of log messages are written and
// which are ignored. Possible values (from most verbose to least verbose) include 'DEBUG', 'TRACE', 'INFO', 'WARNING',
// 'ERROR', and 'NONE'. The provider's logs will be written to the location specified by `providerLogfile`. This can also
// be set through the environment variable `FOREMAN_PROVIDER_LOGLEVEL`. Defaults to `'INFO'`.
func GetProviderLoglevel(ctx *pulumi.Context) string {
	return config.Get(ctx, "foreman:providerLoglevel")
}

// The hostname / IP address of the Foreman REST API server
func GetServerHostname(ctx *pulumi.Context) string {
	return config.Get(ctx, "foreman:serverHostname")
}

// The protocol the Foreman REST API server is using for communication. Defaults to `"https"`.
func GetServerProtocol(ctx *pulumi.Context) string {
	return config.Get(ctx, "foreman:serverProtocol")
}
