// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package foreman

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-foreman/sdk/go/foreman/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDefaulttemplate(ctx *pulumi.Context, args *LookupDefaulttemplateArgs, opts ...pulumi.InvokeOption) (*LookupDefaulttemplateResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDefaulttemplateResult
	err := ctx.Invoke("foreman:index/getDefaulttemplate:getDefaulttemplate", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDefaulttemplate.
type LookupDefaulttemplateArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getDefaulttemplate.
type LookupDefaulttemplateResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id                     string `pulumi:"id"`
	Name                   string `pulumi:"name"`
	OperatingsystemId      int    `pulumi:"operatingsystemId"`
	ProvisioningtemplateId int    `pulumi:"provisioningtemplateId"`
	TemplatekindId         int    `pulumi:"templatekindId"`
}

func LookupDefaulttemplateOutput(ctx *pulumi.Context, args LookupDefaulttemplateOutputArgs, opts ...pulumi.InvokeOption) LookupDefaulttemplateResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupDefaulttemplateResultOutput, error) {
			args := v.(LookupDefaulttemplateArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("foreman:index/getDefaulttemplate:getDefaulttemplate", args, LookupDefaulttemplateResultOutput{}, options).(LookupDefaulttemplateResultOutput), nil
		}).(LookupDefaulttemplateResultOutput)
}

// A collection of arguments for invoking getDefaulttemplate.
type LookupDefaulttemplateOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupDefaulttemplateOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDefaulttemplateArgs)(nil)).Elem()
}

// A collection of values returned by getDefaulttemplate.
type LookupDefaulttemplateResultOutput struct{ *pulumi.OutputState }

func (LookupDefaulttemplateResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDefaulttemplateResult)(nil)).Elem()
}

func (o LookupDefaulttemplateResultOutput) ToLookupDefaulttemplateResultOutput() LookupDefaulttemplateResultOutput {
	return o
}

func (o LookupDefaulttemplateResultOutput) ToLookupDefaulttemplateResultOutputWithContext(ctx context.Context) LookupDefaulttemplateResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupDefaulttemplateResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDefaulttemplateResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDefaulttemplateResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDefaulttemplateResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupDefaulttemplateResultOutput) OperatingsystemId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupDefaulttemplateResult) int { return v.OperatingsystemId }).(pulumi.IntOutput)
}

func (o LookupDefaulttemplateResultOutput) ProvisioningtemplateId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupDefaulttemplateResult) int { return v.ProvisioningtemplateId }).(pulumi.IntOutput)
}

func (o LookupDefaulttemplateResultOutput) TemplatekindId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupDefaulttemplateResult) int { return v.TemplatekindId }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDefaulttemplateResultOutput{})
}
