// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package foreman

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-foreman/sdk/go/foreman/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupKatelloLifecycleEnvironment(ctx *pulumi.Context, args *LookupKatelloLifecycleEnvironmentArgs, opts ...pulumi.InvokeOption) (*LookupKatelloLifecycleEnvironmentResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupKatelloLifecycleEnvironmentResult
	err := ctx.Invoke("foreman:index/getKatelloLifecycleEnvironment:getKatelloLifecycleEnvironment", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getKatelloLifecycleEnvironment.
type LookupKatelloLifecycleEnvironmentArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getKatelloLifecycleEnvironment.
type LookupKatelloLifecycleEnvironmentResult struct {
	__meta_     bool   `pulumi:"__meta_"`
	Description string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id             string `pulumi:"id"`
	Label          string `pulumi:"label"`
	Library        bool   `pulumi:"library"`
	Name           string `pulumi:"name"`
	OrganizationId int    `pulumi:"organizationId"`
	PriorId        int    `pulumi:"priorId"`
	SuccessorId    int    `pulumi:"successorId"`
}

func LookupKatelloLifecycleEnvironmentOutput(ctx *pulumi.Context, args LookupKatelloLifecycleEnvironmentOutputArgs, opts ...pulumi.InvokeOption) LookupKatelloLifecycleEnvironmentResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupKatelloLifecycleEnvironmentResultOutput, error) {
			args := v.(LookupKatelloLifecycleEnvironmentArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("foreman:index/getKatelloLifecycleEnvironment:getKatelloLifecycleEnvironment", args, LookupKatelloLifecycleEnvironmentResultOutput{}, options).(LookupKatelloLifecycleEnvironmentResultOutput), nil
		}).(LookupKatelloLifecycleEnvironmentResultOutput)
}

// A collection of arguments for invoking getKatelloLifecycleEnvironment.
type LookupKatelloLifecycleEnvironmentOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupKatelloLifecycleEnvironmentOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKatelloLifecycleEnvironmentArgs)(nil)).Elem()
}

// A collection of values returned by getKatelloLifecycleEnvironment.
type LookupKatelloLifecycleEnvironmentResultOutput struct{ *pulumi.OutputState }

func (LookupKatelloLifecycleEnvironmentResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupKatelloLifecycleEnvironmentResult)(nil)).Elem()
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) ToLookupKatelloLifecycleEnvironmentResultOutput() LookupKatelloLifecycleEnvironmentResultOutput {
	return o
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) ToLookupKatelloLifecycleEnvironmentResultOutputWithContext(ctx context.Context) LookupKatelloLifecycleEnvironmentResultOutput {
	return o
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) __meta_() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) bool { return v.__meta_ }).(pulumi.BoolOutput)
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) string { return v.Description }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupKatelloLifecycleEnvironmentResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) Label() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) string { return v.Label }).(pulumi.StringOutput)
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) Library() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) bool { return v.Library }).(pulumi.BoolOutput)
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) OrganizationId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) int { return v.OrganizationId }).(pulumi.IntOutput)
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) PriorId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) int { return v.PriorId }).(pulumi.IntOutput)
}

func (o LookupKatelloLifecycleEnvironmentResultOutput) SuccessorId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupKatelloLifecycleEnvironmentResult) int { return v.SuccessorId }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupKatelloLifecycleEnvironmentResultOutput{})
}
