// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package foreman

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-foreman/sdk/go/foreman/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupOperatingsystem(ctx *pulumi.Context, args *LookupOperatingsystemArgs, opts ...pulumi.InvokeOption) (*LookupOperatingsystemResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOperatingsystemResult
	err := ctx.Invoke("foreman:index/getOperatingsystem:getOperatingsystem", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOperatingsystem.
type LookupOperatingsystemArgs struct {
	Title string `pulumi:"title"`
}

// A collection of values returned by getOperatingsystem.
type LookupOperatingsystemResult struct {
	Architectures []int  `pulumi:"architectures"`
	Description   string `pulumi:"description"`
	Family        string `pulumi:"family"`
	// The provider-assigned unique ID for this managed resource.
	Id                    string            `pulumi:"id"`
	Major                 string            `pulumi:"major"`
	Media                 []int             `pulumi:"media"`
	Minor                 string            `pulumi:"minor"`
	Name                  string            `pulumi:"name"`
	Parameters            map[string]string `pulumi:"parameters"`
	Partitiontables       []int             `pulumi:"partitiontables"`
	PasswordHash          string            `pulumi:"passwordHash"`
	ProvisioningTemplates []int             `pulumi:"provisioningTemplates"`
	ReleaseName           string            `pulumi:"releaseName"`
	Title                 string            `pulumi:"title"`
}

func LookupOperatingsystemOutput(ctx *pulumi.Context, args LookupOperatingsystemOutputArgs, opts ...pulumi.InvokeOption) LookupOperatingsystemResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupOperatingsystemResultOutput, error) {
			args := v.(LookupOperatingsystemArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("foreman:index/getOperatingsystem:getOperatingsystem", args, LookupOperatingsystemResultOutput{}, options).(LookupOperatingsystemResultOutput), nil
		}).(LookupOperatingsystemResultOutput)
}

// A collection of arguments for invoking getOperatingsystem.
type LookupOperatingsystemOutputArgs struct {
	Title pulumi.StringInput `pulumi:"title"`
}

func (LookupOperatingsystemOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOperatingsystemArgs)(nil)).Elem()
}

// A collection of values returned by getOperatingsystem.
type LookupOperatingsystemResultOutput struct{ *pulumi.OutputState }

func (LookupOperatingsystemResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOperatingsystemResult)(nil)).Elem()
}

func (o LookupOperatingsystemResultOutput) ToLookupOperatingsystemResultOutput() LookupOperatingsystemResultOutput {
	return o
}

func (o LookupOperatingsystemResultOutput) ToLookupOperatingsystemResultOutputWithContext(ctx context.Context) LookupOperatingsystemResultOutput {
	return o
}

func (o LookupOperatingsystemResultOutput) Architectures() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) []int { return v.Architectures }).(pulumi.IntArrayOutput)
}

func (o LookupOperatingsystemResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupOperatingsystemResultOutput) Family() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.Family }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupOperatingsystemResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupOperatingsystemResultOutput) Major() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.Major }).(pulumi.StringOutput)
}

func (o LookupOperatingsystemResultOutput) Media() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) []int { return v.Media }).(pulumi.IntArrayOutput)
}

func (o LookupOperatingsystemResultOutput) Minor() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.Minor }).(pulumi.StringOutput)
}

func (o LookupOperatingsystemResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupOperatingsystemResultOutput) Parameters() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) map[string]string { return v.Parameters }).(pulumi.StringMapOutput)
}

func (o LookupOperatingsystemResultOutput) Partitiontables() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) []int { return v.Partitiontables }).(pulumi.IntArrayOutput)
}

func (o LookupOperatingsystemResultOutput) PasswordHash() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.PasswordHash }).(pulumi.StringOutput)
}

func (o LookupOperatingsystemResultOutput) ProvisioningTemplates() pulumi.IntArrayOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) []int { return v.ProvisioningTemplates }).(pulumi.IntArrayOutput)
}

func (o LookupOperatingsystemResultOutput) ReleaseName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.ReleaseName }).(pulumi.StringOutput)
}

func (o LookupOperatingsystemResultOutput) Title() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOperatingsystemResult) string { return v.Title }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOperatingsystemResultOutput{})
}
