// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package foreman

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-foreman/sdk/go/foreman/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupParameter(ctx *pulumi.Context, args *LookupParameterArgs, opts ...pulumi.InvokeOption) (*LookupParameterResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupParameterResult
	err := ctx.Invoke("foreman:index/getParameter:getParameter", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getParameter.
type LookupParameterArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getParameter.
type LookupParameterResult struct {
	DomainId    int `pulumi:"domainId"`
	HostId      int `pulumi:"hostId"`
	HostgroupId int `pulumi:"hostgroupId"`
	// The provider-assigned unique ID for this managed resource.
	Id                string `pulumi:"id"`
	Name              string `pulumi:"name"`
	OperatingsystemId int    `pulumi:"operatingsystemId"`
	SubnetId          int    `pulumi:"subnetId"`
	Value             string `pulumi:"value"`
}

func LookupParameterOutput(ctx *pulumi.Context, args LookupParameterOutputArgs, opts ...pulumi.InvokeOption) LookupParameterResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupParameterResultOutput, error) {
			args := v.(LookupParameterArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("foreman:index/getParameter:getParameter", args, LookupParameterResultOutput{}, options).(LookupParameterResultOutput), nil
		}).(LookupParameterResultOutput)
}

// A collection of arguments for invoking getParameter.
type LookupParameterOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupParameterOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupParameterArgs)(nil)).Elem()
}

// A collection of values returned by getParameter.
type LookupParameterResultOutput struct{ *pulumi.OutputState }

func (LookupParameterResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupParameterResult)(nil)).Elem()
}

func (o LookupParameterResultOutput) ToLookupParameterResultOutput() LookupParameterResultOutput {
	return o
}

func (o LookupParameterResultOutput) ToLookupParameterResultOutputWithContext(ctx context.Context) LookupParameterResultOutput {
	return o
}

func (o LookupParameterResultOutput) DomainId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupParameterResult) int { return v.DomainId }).(pulumi.IntOutput)
}

func (o LookupParameterResultOutput) HostId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupParameterResult) int { return v.HostId }).(pulumi.IntOutput)
}

func (o LookupParameterResultOutput) HostgroupId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupParameterResult) int { return v.HostgroupId }).(pulumi.IntOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupParameterResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupParameterResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupParameterResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupParameterResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupParameterResultOutput) OperatingsystemId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupParameterResult) int { return v.OperatingsystemId }).(pulumi.IntOutput)
}

func (o LookupParameterResultOutput) SubnetId() pulumi.IntOutput {
	return o.ApplyT(func(v LookupParameterResult) int { return v.SubnetId }).(pulumi.IntOutput)
}

func (o LookupParameterResultOutput) Value() pulumi.StringOutput {
	return o.ApplyT(func(v LookupParameterResult) string { return v.Value }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupParameterResultOutput{})
}
