// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package foreman

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-foreman/sdk/go/foreman/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Deprecated: foreman.index/getpolicy.getPolicy has been deprecated in favor of foreman.index/getenvironment.getEnvironment
func GetPolicy(ctx *pulumi.Context, args *GetPolicyArgs, opts ...pulumi.InvokeOption) (*GetPolicyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPolicyResult
	err := ctx.Invoke("foreman:index/getPolicy:getPolicy", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPolicy.
type GetPolicyArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getPolicy.
type GetPolicyResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
}

func GetPolicyOutput(ctx *pulumi.Context, args GetPolicyOutputArgs, opts ...pulumi.InvokeOption) GetPolicyResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetPolicyResultOutput, error) {
			args := v.(GetPolicyArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("foreman:index/getPolicy:getPolicy", args, GetPolicyResultOutput{}, options).(GetPolicyResultOutput), nil
		}).(GetPolicyResultOutput)
}

// A collection of arguments for invoking getPolicy.
type GetPolicyOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetPolicyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPolicyArgs)(nil)).Elem()
}

// A collection of values returned by getPolicy.
type GetPolicyResultOutput struct{ *pulumi.OutputState }

func (GetPolicyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetPolicyResult)(nil)).Elem()
}

func (o GetPolicyResultOutput) ToGetPolicyResultOutput() GetPolicyResultOutput {
	return o
}

func (o GetPolicyResultOutput) ToGetPolicyResultOutputWithContext(ctx context.Context) GetPolicyResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetPolicyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetPolicyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetPolicyResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetPolicyResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetPolicyResultOutput{})
}
