// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package foreman

import (
	"context"
	"reflect"

	"github.com/masikrus/pulumi-foreman/sdk/go/foreman/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetTemplatekind(ctx *pulumi.Context, args *GetTemplatekindArgs, opts ...pulumi.InvokeOption) (*GetTemplatekindResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetTemplatekindResult
	err := ctx.Invoke("foreman:index/getTemplatekind:getTemplatekind", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getTemplatekind.
type GetTemplatekindArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getTemplatekind.
type GetTemplatekindResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id   string `pulumi:"id"`
	Name string `pulumi:"name"`
}

func GetTemplatekindOutput(ctx *pulumi.Context, args GetTemplatekindOutputArgs, opts ...pulumi.InvokeOption) GetTemplatekindResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetTemplatekindResultOutput, error) {
			args := v.(GetTemplatekindArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("foreman:index/getTemplatekind:getTemplatekind", args, GetTemplatekindResultOutput{}, options).(GetTemplatekindResultOutput), nil
		}).(GetTemplatekindResultOutput)
}

// A collection of arguments for invoking getTemplatekind.
type GetTemplatekindOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (GetTemplatekindOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTemplatekindArgs)(nil)).Elem()
}

// A collection of values returned by getTemplatekind.
type GetTemplatekindResultOutput struct{ *pulumi.OutputState }

func (GetTemplatekindResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetTemplatekindResult)(nil)).Elem()
}

func (o GetTemplatekindResultOutput) ToGetTemplatekindResultOutput() GetTemplatekindResultOutput {
	return o
}

func (o GetTemplatekindResultOutput) ToGetTemplatekindResultOutputWithContext(ctx context.Context) GetTemplatekindResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o GetTemplatekindResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetTemplatekindResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetTemplatekindResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetTemplatekindResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetTemplatekindResultOutput{})
}
