// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman.Outputs
{

    [OutputType]
    public sealed class ComputeprofileComputeAttribute
    {
        /// <summary>
        /// ID of the compute resource
        /// </summary>
        public readonly int ComputeResourceId;
        /// <summary>
        /// ID of the compute_attribute
        /// </summary>
        public readonly int? Id;
        /// <summary>
        /// Auto-generated name of the compute attribute
        /// </summary>
        public readonly string? Name;
        /// <summary>
        /// VM attributes as JSON
        /// </summary>
        public readonly ImmutableDictionary<string, string>? VmAttrs;

        [OutputConstructor]
        private ComputeprofileComputeAttribute(
            int computeResourceId,

            int? id,

            string? name,

            ImmutableDictionary<string, string>? vmAttrs)
        {
            ComputeResourceId = computeResourceId;
            Id = id;
            Name = name;
            VmAttrs = vmAttrs;
        }
    }
}
