// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman.Outputs
{

    [OutputType]
    public sealed class GetJobtemplateTemplateInputResult
    {
        /// <summary>
        /// @SUMMARY Foreman representation of a template input.
        /// </summary>
        public readonly bool __meta_;
        public readonly bool Advanced;
        public readonly string Default;
        public readonly string Description;
        public readonly string FactName;
        public readonly bool HiddenValue;
        public readonly string Id;
        public readonly string InputType;
        /// <summary>
        /// The name of the template input
        /// </summary>
        public readonly string Name;
        public readonly string PuppetClassName;
        public readonly string PuppetParameterName;
        public readonly bool Required;
        public readonly string ResourceType;
        public readonly int TemplateId;
        public readonly string ValueType;
        public readonly string VariableName;

        [OutputConstructor]
        private GetJobtemplateTemplateInputResult(
            bool __meta_,

            bool advanced,

            string @default,

            string description,

            string factName,

            bool hiddenValue,

            string id,

            string inputType,

            string name,

            string puppetClassName,

            string puppetParameterName,

            bool required,

            string resourceType,

            int templateId,

            string valueType,

            string variableName)
        {
            this.__meta_ = __meta_;
            Advanced = advanced;
            Default = @default;
            Description = description;
            FactName = factName;
            HiddenValue = hiddenValue;
            Id = id;
            InputType = inputType;
            Name = name;
            PuppetClassName = puppetClassName;
            PuppetParameterName = puppetParameterName;
            Required = required;
            ResourceType = resourceType;
            TemplateId = templateId;
            ValueType = valueType;
            VariableName = variableName;
        }
    }
}
