// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman.Outputs
{

    [OutputType]
    public sealed class KatelloContentViewFilterRule
    {
        public readonly string? Architecture;
        public readonly int? Id;
        /// <summary>
        /// Filter pattern of this filter @EXAMPLE apt*
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private KatelloContentViewFilterRule(
            string? architecture,

            int? id,

            string name)
        {
            Architecture = architecture;
            Id = id;
            Name = name;
        }
    }
}
