// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman.Inputs
{

    public sealed class KatelloContentViewFilterArgs : global::Pulumi.ResourceArgs
    {
        [Input("description")]
        public Input<string>? Description { get; set; }

        [Input("id")]
        public Input<int>? Id { get; set; }

        /// <summary>
        /// specifies if content should be included or excluded, default: inclusion=false
        /// </summary>
        [Input("inclusion")]
        public Input<bool>? Inclusion { get; set; }

        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        [Input("rules")]
        private InputList<Inputs.KatelloContentViewFilterRuleArgs>? _rules;
        public InputList<Inputs.KatelloContentViewFilterRuleArgs> Rules
        {
            get => _rules ?? (_rules = new InputList<Inputs.KatelloContentViewFilterRuleArgs>());
            set => _rules = value;
        }

        /// <summary>
        /// Type of this filter, e.g. DEB or RPM
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public KatelloContentViewFilterArgs()
        {
        }
        public static new KatelloContentViewFilterArgs Empty => new KatelloContentViewFilterArgs();
    }
}
