// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Foreman.Inputs
{

    public sealed class ProvisioningtemplateTemplateCombinationsAttributeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The environment ID for this template combination.
        /// </summary>
        [Input("environmentId")]
        public Input<int>? EnvironmentId { get; set; }

        /// <summary>
        /// The hostgroup ID for this template combination.
        /// </summary>
        [Input("hostgroupId")]
        public Input<int>? HostgroupId { get; set; }

        /// <summary>
        /// Template combination unique identifier.
        /// </summary>
        [Input("id")]
        public Input<int>? Id { get; set; }

        public ProvisioningtemplateTemplateCombinationsAttributeArgs()
        {
        }
        public static new ProvisioningtemplateTemplateCombinationsAttributeArgs Empty => new ProvisioningtemplateTemplateCombinationsAttributeArgs();
    }
}
