// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Architecture extends pulumi.CustomResource {
    /**
     * Get an existing Architecture resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: ArchitectureState, opts?: pulumi.CustomResourceOptions): Architecture {
        return new Architecture(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'foreman:index/architecture:Architecture';

    /**
     * Returns true if the given object is an instance of Architecture.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Architecture {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Architecture.__pulumiType;
    }

    /**
     * @SUMMARY Foreman representation of an instruction set architecture (ISA).
     */
    public /*out*/ readonly __meta_!: pulumi.Output<boolean>;
    /**
     * The name of the architecture. Valid characters: ^[A-Za-z0-9-_.]+$. @EXAMPLE "i386"
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * IDs of the operating systems associated with this architecture
     */
    public readonly operatingsystemIds!: pulumi.Output<number[] | undefined>;

    /**
     * Create a Architecture resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ArchitectureArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: ArchitectureArgs | ArchitectureState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as ArchitectureState | undefined;
            resourceInputs["__meta_"] = state ? state.__meta_ : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["operatingsystemIds"] = state ? state.operatingsystemIds : undefined;
        } else {
            const args = argsOrState as ArchitectureArgs | undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["operatingsystemIds"] = args ? args.operatingsystemIds : undefined;
            resourceInputs["__meta_"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Architecture.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Architecture resources.
 */
export interface ArchitectureState {
    /**
     * @SUMMARY Foreman representation of an instruction set architecture (ISA).
     */
    __meta_?: pulumi.Input<boolean>;
    /**
     * The name of the architecture. Valid characters: ^[A-Za-z0-9-_.]+$. @EXAMPLE "i386"
     */
    name?: pulumi.Input<string>;
    /**
     * IDs of the operating systems associated with this architecture
     */
    operatingsystemIds?: pulumi.Input<pulumi.Input<number>[]>;
}

/**
 * The set of arguments for constructing a Architecture resource.
 */
export interface ArchitectureArgs {
    /**
     * The name of the architecture. Valid characters: ^[A-Za-z0-9-_.]+$. @EXAMPLE "i386"
     */
    name?: pulumi.Input<string>;
    /**
     * IDs of the operating systems associated with this architecture
     */
    operatingsystemIds?: pulumi.Input<pulumi.Input<number>[]>;
}
