// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getArchitecture(args: GetArchitectureArgs, opts?: pulumi.InvokeOptions): Promise<GetArchitectureResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getArchitecture:getArchitecture", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getArchitecture.
 */
export interface GetArchitectureArgs {
    name: string;
}

/**
 * A collection of values returned by getArchitecture.
 */
export interface GetArchitectureResult {
    readonly __meta_: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly operatingsystemIds: number[];
}
export function getArchitectureOutput(args: GetArchitectureOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetArchitectureResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getArchitecture:getArchitecture", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getArchitecture.
 */
export interface GetArchitectureOutputArgs {
    name: pulumi.Input<string>;
}
