// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDefaulttemplate(args: GetDefaulttemplateArgs, opts?: pulumi.InvokeOptions): Promise<GetDefaulttemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getDefaulttemplate:getDefaulttemplate", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDefaulttemplate.
 */
export interface GetDefaulttemplateArgs {
    name: string;
}

/**
 * A collection of values returned by getDefaulttemplate.
 */
export interface GetDefaulttemplateResult {
    readonly __meta_: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
    readonly operatingsystemId: number;
    readonly provisioningtemplateId: number;
    readonly templatekindId: number;
}
export function getDefaulttemplateOutput(args: GetDefaulttemplateOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDefaulttemplateResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getDefaulttemplate:getDefaulttemplate", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDefaulttemplate.
 */
export interface GetDefaulttemplateOutputArgs {
    name: pulumi.Input<string>;
}
