// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getKatelloSyncPlan(args: GetKatelloSyncPlanArgs, opts?: pulumi.InvokeOptions): Promise<GetKatelloSyncPlanResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getKatelloSyncPlan:getKatelloSyncPlan", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKatelloSyncPlan.
 */
export interface GetKatelloSyncPlanArgs {
    name: string;
}

/**
 * A collection of values returned by getKatelloSyncPlan.
 */
export interface GetKatelloSyncPlanResult {
    readonly __meta_: boolean;
    readonly cronExpression: string;
    readonly description: string;
    readonly enabled: boolean;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly interval: string;
    readonly name: string;
    readonly syncDate: string;
}
export function getKatelloSyncPlanOutput(args: GetKatelloSyncPlanOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKatelloSyncPlanResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getKatelloSyncPlan:getKatelloSyncPlan", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKatelloSyncPlan.
 */
export interface GetKatelloSyncPlanOutputArgs {
    name: pulumi.Input<string>;
}
