// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getKatelloContentCredential(args: GetKatelloContentCredentialArgs, opts?: pulumi.InvokeOptions): Promise<GetKatelloContentCredentialResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getKatelloContentCredential:getKatelloContentCredential", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKatelloContentCredential.
 */
export interface GetKatelloContentCredentialArgs {
    name: string;
}

/**
 * A collection of values returned by getKatelloContentCredential.
 */
export interface GetKatelloContentCredentialResult {
    readonly __meta_: boolean;
    readonly content: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
}
export function getKatelloContentCredentialOutput(args: GetKatelloContentCredentialOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKatelloContentCredentialResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getKatelloContentCredential:getKatelloContentCredential", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKatelloContentCredential.
 */
export interface GetKatelloContentCredentialOutputArgs {
    name: pulumi.Input<string>;
}
