// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getKatelloLifecycleEnvironment(args: GetKatelloLifecycleEnvironmentArgs, opts?: pulumi.InvokeOptions): Promise<GetKatelloLifecycleEnvironmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getKatelloLifecycleEnvironment:getKatelloLifecycleEnvironment", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKatelloLifecycleEnvironment.
 */
export interface GetKatelloLifecycleEnvironmentArgs {
    name: string;
}

/**
 * A collection of values returned by getKatelloLifecycleEnvironment.
 */
export interface GetKatelloLifecycleEnvironmentResult {
    readonly __meta_: boolean;
    readonly description: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly label: string;
    readonly library: boolean;
    readonly name: string;
    readonly organizationId: number;
    readonly priorId: number;
    readonly successorId: number;
}
export function getKatelloLifecycleEnvironmentOutput(args: GetKatelloLifecycleEnvironmentOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetKatelloLifecycleEnvironmentResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getKatelloLifecycleEnvironment:getKatelloLifecycleEnvironment", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getKatelloLifecycleEnvironment.
 */
export interface GetKatelloLifecycleEnvironmentOutputArgs {
    name: pulumi.Input<string>;
}
