// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getOperatingsystem(args: GetOperatingsystemArgs, opts?: pulumi.InvokeOptions): Promise<GetOperatingsystemResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getOperatingsystem:getOperatingsystem", {
        "title": args.title,
    }, opts);
}

/**
 * A collection of arguments for invoking getOperatingsystem.
 */
export interface GetOperatingsystemArgs {
    title: string;
}

/**
 * A collection of values returned by getOperatingsystem.
 */
export interface GetOperatingsystemResult {
    readonly __meta_: boolean;
    readonly architectures: number[];
    readonly description: string;
    readonly family: string;
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly major: string;
    readonly media: number[];
    readonly minor: string;
    readonly name: string;
    readonly parameters: {[key: string]: string};
    readonly partitiontables: number[];
    readonly passwordHash: string;
    readonly provisioningTemplates: number[];
    readonly releaseName: string;
    readonly title: string;
}
export function getOperatingsystemOutput(args: GetOperatingsystemOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOperatingsystemResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getOperatingsystem:getOperatingsystem", {
        "title": args.title,
    }, opts);
}

/**
 * A collection of arguments for invoking getOperatingsystem.
 */
export interface GetOperatingsystemOutputArgs {
    title: pulumi.Input<string>;
}
