// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/** @deprecated foreman.index/getpolicy.getPolicy has been deprecated in favor of foreman.index/getenvironment.getEnvironment */
export function getPolicy(args: GetPolicyArgs, opts?: pulumi.InvokeOptions): Promise<GetPolicyResult> {
    pulumi.log.warn("getPolicy is deprecated: foreman.index/getpolicy.getPolicy has been deprecated in favor of foreman.index/getenvironment.getEnvironment")
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getPolicy:getPolicy", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicy.
 */
export interface GetPolicyArgs {
    name: string;
}

/**
 * A collection of values returned by getPolicy.
 */
export interface GetPolicyResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
}
/** @deprecated foreman.index/getpolicy.getPolicy has been deprecated in favor of foreman.index/getenvironment.getEnvironment */
export function getPolicyOutput(args: GetPolicyOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPolicyResult> {
    pulumi.log.warn("getPolicy is deprecated: foreman.index/getpolicy.getPolicy has been deprecated in favor of foreman.index/getenvironment.getEnvironment")
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getPolicy:getPolicy", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPolicy.
 */
export interface GetPolicyOutputArgs {
    name: pulumi.Input<string>;
}
