// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getPuppetclass(args: GetPuppetclassArgs, opts?: pulumi.InvokeOptions): Promise<GetPuppetclassResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getPuppetclass:getPuppetclass", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPuppetclass.
 */
export interface GetPuppetclassArgs {
    name: string;
}

/**
 * A collection of values returned by getPuppetclass.
 */
export interface GetPuppetclassResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly name: string;
}
export function getPuppetclassOutput(args: GetPuppetclassOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetPuppetclassResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getPuppetclass:getPuppetclass", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getPuppetclass.
 */
export interface GetPuppetclassOutputArgs {
    name: pulumi.Input<string>;
}
