// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getTemplateinput(opts?: pulumi.InvokeOptions): Promise<GetTemplateinputResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("foreman:index/getTemplateinput:getTemplateinput", {
    }, opts);
}

/**
 * A collection of values returned by getTemplateinput.
 */
export interface GetTemplateinputResult {
    readonly __meta_: boolean;
    readonly advanced: boolean;
    readonly default: string;
    readonly description: string;
    readonly factName: string;
    readonly hiddenValue: boolean;
    readonly id: string;
    readonly inputType: string;
    readonly name: string;
    readonly puppetClassName: string;
    readonly puppetParameterName: string;
    readonly required: boolean;
    readonly resourceType: string;
    readonly templateId: number;
    readonly valueType: string;
    readonly variableName: string;
}
export function getTemplateinputOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTemplateinputResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("foreman:index/getTemplateinput:getTemplateinput", {
    }, opts);
}
