// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OverrideValue extends pulumi.CustomResource {
    /**
     * Get an existing OverrideValue resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OverrideValueState, opts?: pulumi.CustomResourceOptions): OverrideValue {
        return new OverrideValue(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'foreman:index/overrideValue:OverrideValue';

    /**
     * Returns true if the given object is an instance of OverrideValue.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OverrideValue {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OverrideValue.__pulumiType;
    }

    /**
     * @SUMMARY Smart class parameter override value.
     */
    public /*out*/ readonly __meta_!: pulumi.Output<boolean>;
    /**
     * A map containing the match criteria. Must contain two keys: `type` and `value`.Type can be one of `fqdn`, `hostgroup`,
     * `domain` or `os`@EXAMPLE { type = "hostgroup" value = "exampleGroup" }
     */
    public readonly match!: pulumi.Output<{[key: string]: string}>;
    /**
     * When set to `true` Foreman will not send this parameter in classification output. Default value is `false`.@EXAMPLE
     * false
     */
    public readonly omit!: pulumi.Output<boolean | undefined>;
    /**
     * ID of the smart class parameter to override.@EXAMPLE 1
     */
    public readonly smartClassParameterId!: pulumi.Output<number>;
    /**
     * Smart parameter override value. Hashes and arrays must be JSON encoded.@EXAMPLE jsonencode({ key = "value" })
     */
    public readonly value!: pulumi.Output<string>;

    /**
     * Create a OverrideValue resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OverrideValueArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OverrideValueArgs | OverrideValueState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OverrideValueState | undefined;
            resourceInputs["__meta_"] = state ? state.__meta_ : undefined;
            resourceInputs["match"] = state ? state.match : undefined;
            resourceInputs["omit"] = state ? state.omit : undefined;
            resourceInputs["smartClassParameterId"] = state ? state.smartClassParameterId : undefined;
            resourceInputs["value"] = state ? state.value : undefined;
        } else {
            const args = argsOrState as OverrideValueArgs | undefined;
            if ((!args || args.match === undefined) && !opts.urn) {
                throw new Error("Missing required property 'match'");
            }
            if ((!args || args.smartClassParameterId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'smartClassParameterId'");
            }
            if ((!args || args.value === undefined) && !opts.urn) {
                throw new Error("Missing required property 'value'");
            }
            resourceInputs["match"] = args ? args.match : undefined;
            resourceInputs["omit"] = args ? args.omit : undefined;
            resourceInputs["smartClassParameterId"] = args ? args.smartClassParameterId : undefined;
            resourceInputs["value"] = args ? args.value : undefined;
            resourceInputs["__meta_"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OverrideValue.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering OverrideValue resources.
 */
export interface OverrideValueState {
    /**
     * @SUMMARY Smart class parameter override value.
     */
    __meta_?: pulumi.Input<boolean>;
    /**
     * A map containing the match criteria. Must contain two keys: `type` and `value`.Type can be one of `fqdn`, `hostgroup`,
     * `domain` or `os`@EXAMPLE { type = "hostgroup" value = "exampleGroup" }
     */
    match?: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * When set to `true` Foreman will not send this parameter in classification output. Default value is `false`.@EXAMPLE
     * false
     */
    omit?: pulumi.Input<boolean>;
    /**
     * ID of the smart class parameter to override.@EXAMPLE 1
     */
    smartClassParameterId?: pulumi.Input<number>;
    /**
     * Smart parameter override value. Hashes and arrays must be JSON encoded.@EXAMPLE jsonencode({ key = "value" })
     */
    value?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a OverrideValue resource.
 */
export interface OverrideValueArgs {
    /**
     * A map containing the match criteria. Must contain two keys: `type` and `value`.Type can be one of `fqdn`, `hostgroup`,
     * `domain` or `os`@EXAMPLE { type = "hostgroup" value = "exampleGroup" }
     */
    match: pulumi.Input<{[key: string]: pulumi.Input<string>}>;
    /**
     * When set to `true` Foreman will not send this parameter in classification output. Default value is `false`.@EXAMPLE
     * false
     */
    omit?: pulumi.Input<boolean>;
    /**
     * ID of the smart class parameter to override.@EXAMPLE 1
     */
    smartClassParameterId: pulumi.Input<number>;
    /**
     * Smart parameter override value. Hashes and arrays must be JSON encoded.@EXAMPLE jsonencode({ key = "value" })
     */
    value: pulumi.Input<string>;
}
