# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetComputeprofileResult',
    'AwaitableGetComputeprofileResult',
    'get_computeprofile',
    'get_computeprofile_output',
]

@pulumi.output_type
class GetComputeprofileResult:
    """
    A collection of values returned by getComputeprofile.
    """
    def __init__(__self__, __meta_=None, compute_attributes=None, id=None, name=None):
        if __meta_ and not isinstance(__meta_, bool):
            raise TypeError("Expected argument '__meta_' to be a bool")
        pulumi.set(__self__, "__meta_", __meta_)
        if compute_attributes and not isinstance(compute_attributes, list):
            raise TypeError("Expected argument 'compute_attributes' to be a list")
        pulumi.set(__self__, "compute_attributes", compute_attributes)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def __meta_(self) -> bool:
        return pulumi.get(self, "__meta_")

    @property
    @pulumi.getter(name="computeAttributes")
    def compute_attributes(self) -> Sequence['outputs.GetComputeprofileComputeAttributeResult']:
        return pulumi.get(self, "compute_attributes")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")


class AwaitableGetComputeprofileResult(GetComputeprofileResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetComputeprofileResult(
            __meta_=self.__meta_,
            compute_attributes=self.compute_attributes,
            id=self.id,
            name=self.name)


def get_computeprofile(name: Optional[str] = None,
                       opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetComputeprofileResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('foreman:index/getComputeprofile:getComputeprofile', __args__, opts=opts, typ=GetComputeprofileResult).value

    return AwaitableGetComputeprofileResult(
        __meta_=pulumi.get(__ret__, '__meta_'),
        compute_attributes=pulumi.get(__ret__, 'compute_attributes'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'))
def get_computeprofile_output(name: Optional[pulumi.Input[str]] = None,
                              opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetComputeprofileResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('foreman:index/getComputeprofile:getComputeprofile', __args__, opts=opts, typ=GetComputeprofileResult)
    return __ret__.apply(lambda __response__: GetComputeprofileResult(
        __meta_=pulumi.get(__response__, '__meta_'),
        compute_attributes=pulumi.get(__response__, 'compute_attributes'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name')))
