# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetKatelloContentCredentialResult',
    'AwaitableGetKatelloContentCredentialResult',
    'get_katello_content_credential',
    'get_katello_content_credential_output',
]

@pulumi.output_type
class GetKatelloContentCredentialResult:
    """
    A collection of values returned by getKatelloContentCredential.
    """
    def __init__(__self__, __meta_=None, content=None, id=None, name=None):
        if __meta_ and not isinstance(__meta_, bool):
            raise TypeError("Expected argument '__meta_' to be a bool")
        pulumi.set(__self__, "__meta_", __meta_)
        if content and not isinstance(content, str):
            raise TypeError("Expected argument 'content' to be a str")
        pulumi.set(__self__, "content", content)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)

    @property
    @pulumi.getter
    def __meta_(self) -> bool:
        return pulumi.get(self, "__meta_")

    @property
    @pulumi.getter
    def content(self) -> str:
        return pulumi.get(self, "content")

    @property
    @pulumi.getter
    def id(self) -> str:
        """
        The provider-assigned unique ID for this managed resource.
        """
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")


class AwaitableGetKatelloContentCredentialResult(GetKatelloContentCredentialResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetKatelloContentCredentialResult(
            __meta_=self.__meta_,
            content=self.content,
            id=self.id,
            name=self.name)


def get_katello_content_credential(name: Optional[str] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetKatelloContentCredentialResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('foreman:index/getKatelloContentCredential:getKatelloContentCredential', __args__, opts=opts, typ=GetKatelloContentCredentialResult).value

    return AwaitableGetKatelloContentCredentialResult(
        __meta_=pulumi.get(__ret__, '__meta_'),
        content=pulumi.get(__ret__, 'content'),
        id=pulumi.get(__ret__, 'id'),
        name=pulumi.get(__ret__, 'name'))
def get_katello_content_credential_output(name: Optional[pulumi.Input[str]] = None,
                                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetKatelloContentCredentialResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['name'] = name
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('foreman:index/getKatelloContentCredential:getKatelloContentCredential', __args__, opts=opts, typ=GetKatelloContentCredentialResult)
    return __ret__.apply(lambda __response__: GetKatelloContentCredentialResult(
        __meta_=pulumi.get(__response__, '__meta_'),
        content=pulumi.get(__response__, 'content'),
        id=pulumi.get(__response__, 'id'),
        name=pulumi.get(__response__, 'name')))
